### ISSUE TITLE
Doesn't work with Xcode 7.2

### ISSUE THREAD

**Issue by tomassliz** [k0nserv/luft#19]
I installed Luft via Alcatraz and when I quit Xcode and run it again, Luft is not loaded.

**Comment by k0nserv** [comment]
Hi @tomassliz this is because I haven't added the UUID of Xcode 7.2 to yet. I don't have 7.2 on my machine yet, but if you could [figure it out](http://isobar.logdown.com/posts/241755-how-to-get-the-xcode-uuid-for-plugins) and post it here  I'll add it. Alternatively you could make a PR adding it to [Info.plist](https://github.com/k0nserv/luft/blob/master/Luft/Info.plist)

**Comment by bogren** [comment]
Fixed in #20 :v:

**Comment by k0nserv** [comment]
@tomassliz Please retry and it should work now

**Comment by tomassliz** [comment]
It works now. Thank you 👍
